version: '3.8'

services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.9.2  # Use the latest MLflow version
    container_name: mlflow
    ports:
      - "5000:5000"  # Expose MLflow on localhost:5000
    environment:
      - MLFLOW_BACKEND_STORE_URI=sqlite:///mlflow.db  # Store metadata in SQLite
      - MLFLOW_ARTIFACT_ROOT=/mlruns  # Path for storing models
    volumes:
      - ./mlruns:/mlruns  # Persist MLflow runs
      - ./mlflow.db:/mlflow.db  # Persist the database

  fastapi:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"  # Expose FastAPI on localhost:8000
    depends_on:
      - mlflow  # Ensure MLflow starts first
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000  # Connect FastAPI to MLflow